# Generated by Django 5.2.5 on 2025-08-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='item_type',
            field=models.CharField(blank=True, choices=[('Battery', 'Pil'), ('Ear_Tip', 'Kulak Ucu'), ('Tube', 'Tüp'), ('Filter', 'Filtre'), ('Wax_Guard', 'Kulak Kiri Koruması'), ('Accessory', 'Aksesuar'), ('Other', 'Diğer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
