# Generated by Django 5.2.5 on 2025-08-08 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('consultation', 'Konsültasyon'), ('hearing_test', 'İşitme Testi'), ('device_fitting', 'Cihaz Uygulaması'), ('follow_up', 'Kontrol'), ('maintenance', 'Bakım')], default='consultation', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Planlandı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
