# Generated by Django 5.2.5 on 2025-08-06 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HearingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField()),
                ('test_type', models.CharField(choices=[('Pure_Tone', 'Saf Ses Odyometrisi'), ('Speech', 'Konuşma Odyometrisi'), ('Impedance', 'Empedans Odyometrisi'), ('ABR', 'İşitsel Beyin Sapı Yanıtı'), ('OAE', 'Otoakustik Emisyon'), ('Other', 'Diğer')], max_length=50)),
                ('right_ear_250', models.IntegerField(blank=True, null=True)),
                ('right_ear_500', models.IntegerField(blank=True, null=True)),
                ('right_ear_1000', models.IntegerField(blank=True, null=True)),
                ('right_ear_2000', models.IntegerField(blank=True, null=True)),
                ('right_ear_4000', models.IntegerField(blank=True, null=True)),
                ('right_ear_8000', models.IntegerField(blank=True, null=True)),
                ('left_ear_250', models.IntegerField(blank=True, null=True)),
                ('left_ear_500', models.IntegerField(blank=True, null=True)),
                ('left_ear_1000', models.IntegerField(blank=True, null=True)),
                ('left_ear_2000', models.IntegerField(blank=True, null=True)),
                ('left_ear_4000', models.IntegerField(blank=True, null=True)),
                ('left_ear_8000', models.IntegerField(blank=True, null=True)),
                ('right_ear_srt', models.IntegerField(blank=True, null=True)),
                ('left_ear_srt', models.IntegerField(blank=True, null=True)),
                ('right_ear_sds', models.IntegerField(blank=True, null=True)),
                ('left_ear_sds', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Completed', 'Tamamlandı'), ('Incomplete', 'Tamamlanmadı'), ('Cancelled', 'İptal Edildi')], default='Completed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearing_tests', to='patients.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearing_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
    ]
