# Generated by Django 5.2.5 on 2025-08-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearing_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearingtest',
            name='report_pdf',
            field=models.FileField(blank=True, help_text='Test raporu PDF dosyası', null=True, upload_to='test_reports/'),
        ),
    ]
