# Generated by Django 5.2.5 on 2025-08-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hasta', 'verbose_name_plural': 'Hastalar'},
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Alerjiler'),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_medications',
            field=models.TextField(blank=True, verbose_name='Mevcut İlaçlar'),
        ),
        migrations.AddField(
            model_name='patient',
            name='district',
            field=models.CharField(blank=True, max_length=50, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Acil Durum İletişim Kişisi'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Acil Durum Telefonu'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hearing_aid_brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='İşitme Cihazı Markası'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hearing_aid_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='İşitme Cihazı Modeli'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hearing_aid_serial',
            field=models.CharField(blank=True, max_length=100, verbose_name='İşitme Cihazı Seri No'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hearing_aid_type',
            field=models.CharField(blank=True, choices=[('BTE', 'BTE (Kulak Arkası)'), ('ITE', 'ITE (Kulak İçi)'), ('ITC', 'ITC (Kulak Kanalı)'), ('CIC', 'CIC (Tam Gizli)'), ('RIC', 'RIC (Kulak Arkası Açık)'), ('None', 'Kullanmıyor')], max_length=10, verbose_name='İşitme Cihazı Türü'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sigorta Numarası'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sigorta Sağlayıcısı'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Son Randevu Tarihi'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, verbose_name='Tıbbi Geçmiş'),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sonraki Randevu Tarihi'),
        ),
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Meslek'),
        ),
        migrations.AddField(
            model_name='patient',
            name='referring_doctor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sevk Eden Doktor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='tc_number',
            field=models.CharField(default='00000000000', max_length=11, verbose_name='TC Kimlik No'),
        ),
        migrations.AddField(
            model_name='patient',
            name='total_appointments',
            field=models.IntegerField(default=0, verbose_name='Toplam Randevu Sayısı'),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Erkek'), ('F', 'Kadın')], max_length=1, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Pasif')], default='active', max_length=10, verbose_name='Durum'),
        ),
    ]
